### ISSUE TITLE
Remove GSAP?

### ISSUE THREAD

**Issue by hackuun** [pirony/ks-vue-scrollmagic#4]
Hello. Thanks for great work with this plugin.

Is there any chance to use this plugin with Velocity instead of GSAP?

**Comment by pirony** [comment]
Hi & thx @iamdubx,
sadly It's not possible atm because Scrollmagic's Velocity plugin is not yet implemented... I' ll integrate it in the next release, but I miss some time so I think It won't be possible 'til January. Stay tuned

**Comment by hackuun** [comment]
@pirony cool and thanks!
